# Generated by Django 2.2.4 on 2021-01-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asciify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
